name: Setup, Build, & Publish to DockerHub .Net Project as Artifact with Aws Code Artifact as Nuget Package Manager

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      project-name:
        description: Work Directory begins at /home/runner/work/ - Uses Project name with .Net default folder naming convention if not specified
        type: string
        default: "none"
      migration-folder-path:
        description: Work Directory begins at /home/runner/work/ - Uses Project name with .Net default folder naming convention if not specified
        type: string
        default: "Data/Migrations"
      double-folder-path:
        description: Uses .Net default folder naming convention "ProjectName/ProjectName/*.csproj"
        type: boolean
        default: true
      context-path-values:
        description: Comma seperated string of Context Names to migrate to the database "contex-1,context-2"
        type: string
    secrets:
      DB_CONNECTION_STRING:
        description: Postgres DB Connection String
        required: true

jobs:
  sanitize-context-paths:
    runs-on: ubuntu-latest
    outputs:
      context-path-values: ${{ steps.prepare-context-paths.outputs.context-path-values }}
    steps:
      - name: Prepare context-paths values in bash
        id: prepare-context-paths
        run: |
          # Capture the input
          context_path_values="${{ inputs.context-path-values }}"

          # Split the input by comma into a Bash array
          IFS=',' read -r -a array <<< "$context_path_values"

          cleaned_array=()
          for element in "${array[@]}"; do
            cleaned_element=$(echo "$element" | sed 's/^[ \t]*//;s/[ \t]*$//')
            cleaned_array+=("$cleaned_element")
          done

          # Convert the array into compact JSON format (without pretty-printing)
          json_array=$(printf '%s\n' "${cleaned_array[@]}" | jq -R . | jq -s -c .)

          # Set the compact JSON array as output and as an environment variable
          echo "context-paths values: $json_array"
          echo "::set-output name=context-path-values::$json_array"
          echo "CONTEXT_PATH_VALUES=$json_array" >> $GITHUB_ENV

  update_database_migrations:
    needs: sanitize-context-paths
    runs-on: ${{ inputs.runs-on }}
    if: ${{ needs.sanitize-context-paths.outputs.context-path-values != '[]' }}
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.sanitize-context-paths.outputs['context-path-values']) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Dotnet and Install ef core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet tool install --global dotnet-ef

      - name: Verify EF-Core installation & update
        run: |
          export PATH=$PATH:$HOME/.dotnet/tools
          source ~/.bashrc
          dotnet ef --version

      - name: Get Code Artifact Token
        run: |
          mkdir ~/.aws && cd ~/.aws
          echo [github-actions] > ./config
          echo region = us-west-2 >> ./config
          echo output = json >> ./config
          echo [github-actions] > ./credentials
          echo aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} >> ./credentials
          echo aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ./credentials
          echo aws_region=${{ secrets.AWS_REGION }} >> ./credentials

      - name: Get Code Artifact Token
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain fullstackindie --domain-owner 896630178141 --query authorizationToken --output text --profile github-actions`

      - name: Setup Aws as Nuget
        run: |
          aws codeartifact login --tool dotnet --domain fullstackindie --domain-owner 896630178141 --repository fullstackindie --profile github-actions
          aws codeartifact list-packages --domain fullstackindie --repository fullstackindie --profile github-actions

      - name: Cache Nuget Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Use context-paths value
        run: |
          echo "context-paths value: ${{ matrix.value }}"

      - name: Setup project path
        if: ${{ inputs.double-folder-path  == true }}
        run: |
          echo "PROJECT_PATH=${{ inputs.project-name }}/${{ inputs.project-name }}" >> $GITHUB_ENV

      - name: Setup project path
        if: ${{ inputs.double-folder-path == false }}
        run: |
          echo "PROJECT_PATH=${{ inputs.project-name }}" >> $GITHUB_ENV

      - name: Verify environment variables
        run: |
          echo "PROJECT_PATH  : ${{ env.PROJECT_PATH }}"

      - name: Verify EF-Core installation & update
        run: |
          dotnet ef
          dotnet ef database update --verbose --project="${{ inputs.project-name }}" --context=${{ matrix.value }} --connection ${{ secrets.DB_CONNECTION_STRING}}
