name: >-
  Publish static Website into Production Server
  
'on':
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      folder_path:
        description: Folder to create website in
        type: string
        required: true  
      owner_name:
        description: NAme of owner or organization
        type: string
        required: true 
      repo_name:
        description: Name of repo
        type: string
        required: true
        description: Name of repo
        type: string
        required: true
        
    secrets:
      SERVER_SSH_HOST:
        description: Server IP to deploy on
        required: true
      SERVER_SSH_USERNAME:
        description: Server user
        required: true
      SERVER_SSH_KEY:
        description: Server ssh key
        required: true
      SERVER_SSH_PASSPHRASE:
        description: Server ssh key passphrase
        required: true
      SERVER_SSH_PORT:
        description: Server port to ssh into
        required: true
 

jobs:
  download-build-docker-image:
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: SSH into Dev Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            mkdir -p ${{ inputs.folder_path }}
            cd ${{ inputs.folder_path }}
            rm -r ./*
            git clone ssh://git@github/${{ inputs.owner_name }}/${{ inputs.repo_name}}.git
            rm -r ./AdminDashboard/.git*
            chown -R www-data:www-data ${{ inputs.repo_name}}
            systemctl reload nginx
            exit
