name: >-
  Publish static Website into Production Server
  
on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      folder_path:
        description: Folder to create website in
        type: string
        required: true  
      owner_name:
        description: NAme of owner or organization
        type: string
        required: true 
      repo_name:
        description: Name of repo
        type: string
        required: true
        
    secrets:
      SERVER_SSH_HOST:
        description: Server IP to deploy on
        required: true
      SERVER_SSH_USERNAME:
        description: Server user
        required: true
      SERVER_SSH_KEY:
        description: Server ssh key
        required: true
      SERVER_SSH_PORT:
        description: Server port to ssh into
        required: true
 

jobs:
  rsync-updates-to-server:
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Deply with rsync 
      uses: burnett01/rsync-deployments@5.2.1
      env: 
        DEPLOY_FOLDER: ${{ inputs.folder_path }}/deploy
      with:
        # use --mkpath if using Ubuntu 22.04 - --mkpath not supported in rsync 3.1.3 Ubuntu 20.04 GitHub Action Runner
        switches: -avzr --delete  --cvs-exclude --rsync-path="mkdir -p $DEPLOY_FOLDER && rsync" 
        path: $GITHUB_WORKSPACE
        remote_path: $DEPLOY_FOLDER
        remote_host: ${{ secrets.SERVER_SSH_HOST }}
        remote_user: ${{ secrets.SERVER_SSH_USERNAME }}
        remote_port: ${{ secrets.SERVER_SSH_PORT }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}

  ssh-deploy-website:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: SSH into Dev Server
        uses: appleboy/ssh-action@v0.1.7
        env: 
          DEPLOY_FOLDER: ${{ inputs.folder_path }}/deploy
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          envs: DEPLOY_FOLDER
          script: |
            chown -R www-data:www-data $DEPLOY_FOLDER
            mkdir -p ${{ inputs.folder_path }}
            rm -r ${{ inputs.folder_path }}/*
            cp -r $DEPLOY_FOLDER ${{ inputs.folder_path }}/
            chown -R www-data:www-data ${{ inputs.folder_path }}
            systemctl reload nginx
            exit
            

